"""
Abstract base class for AI providers.
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)

class AIProvider(ABC):
    """Abstract base class for AI providers."""

    @abstractmethod
    async def generate_text(self, prompt: str, **kwargs) -> str:
        """Generate text from a prompt."""
        pass

    @abstractmethod
    async def generate_briefing(self, data: Dict[str, Any]) -> str:
        """Generate a situation briefing from data."""
        pass

class MockAIProvider(AIProvider):
    """Mock AI provider for development and testing."""

    async def generate_text(self, prompt: str, **kwargs) -> str:
        """Generate mock text response."""
        logger.info(f"Mock AI provider generating text for prompt: {prompt[:50]}...")
        return f"Mock AI response to: {prompt[:100]}..."

    async def generate_briefing(self, data: Dict[str, Any]) -> str:
        """Generate a mock situation briefing."""
        logger.info("Mock AI provider generating situation briefing")

        # Extract key information from data
        zones = data.get('zones', [])
        reports = data.get('reports', [])
        detections = data.get('detections', [])
        resources = data.get('resources', [])
        mesh_status = data.get('mesh_status', {})

        # Count critical elements
        critical_zones = [z for z in zones if z.get('risk_score', 0) >= 80]
        high_priority_reports = [r for r in reports if r.get('severity') in ['HIGH', 'CRITICAL']]
        survivor_detections = [d for d in detections if d.get('class') == 'person']
        fire_detections = [d for d in detections if d.get('class') == 'fire']

        briefing = f"""
**SITUATION BRIEFING - RESQLINK**
Generated at: {data.get('timestamp', 'Unknown')}

**1. SITUATION SUMMARY**
{len(zones)} zones analyzed, {len(critical_zones)} critical zones identified.
{len(reports)} incident reports received, {len(high_priority_reports)} requiring immediate attention.
{len(detections)} AI detections processed, including {len(survivor_detections)} potential survivors and {len(fire_detections)} fire detections.

**2. CRITICAL INCIDENTS**
"""

        if critical_zones:
            for i, zone in enumerate(critical_zones[:3]):  # Show top 3
                briefing += f"- Zone {zone.get('name', f'Zone-{i+1}')}: Risk Score {zone.get('risk_score', 0)} - "
                factors = []
                if zone.get('survivors', 0) > 0:
                    factors.append(f"{zone['survivors']} survivors detected")
                if zone.get('fires', 0) > 0:
                    factors.append(f"{zone['fires']} active fire(s)")
                if zone.get('damage', 0) > 0:
                    factors.append(f"{zone['damage']} structural damage indicator(s)")
                if zone.get('reports', 0) > 0:
                    factors.append(f"{zone['reports']} field reports")
                briefing += ", ".join(factors) + "\n"
        else:
            briefing += "- No critical zones currently identified\n"

        briefing += """
**3. SURVIVOR STATUS**
- Total Potential Survivors Detected: {survivor_count}
- High Confidence Detections: {high_conf_count}

**4. FIRE/STRUCTURAL HAZARDS**
- Active Fire Detections: {fire_count}
- Structural Damage Indicators: {damage_count}

**5. RESOURCE STATUS**
- Available Resources: {available_resources}
- Deployed Resources: {deployed_resources}

**6. COMMUNICATION STATUS**
- Mesh Network: {mesh_status}
- Internet Connectivity: {internet_status}

**7. RECOMMENDED ACTIONS**
{recommendations}

**NOTE: This briefing is generated by AI decision support systems. All recommendations should be reviewed by qualified emergency personnel before implementation.**
""".format(
            survivor_count=len(survivor_detections),
            high_conf_count=len([d for d in survivor_detections if d.get('confidence', 0) > 0.8]),
            fire_count=len(fire_detections),
            damage_count=len([d for d in detections if d.get('class') in ['earthquake', 'collapse', 'damage']]),
            available_resources=len([r for r in resources if r.get('availability', False)]),
            deployed_resources=len([r for r in resources if not r.get('availability', True)]),
            mesh_status="ACTIVE" if mesh_status.get('connected', False) else "LIMITED",
            internet_status="ONLINE" if data.get('internet_available', True) else "OFFLINE",
            recommendations="• Deploy SAR teams to critical zones\n• Establish medical triage centers\n• Initiate evacuation procedures for high-risk areas\n• Coordinate fire suppression efforts\n• Maintain communication with all field units"
        )

        return briefing.strip()

"""
Real AI provider implementations would go here for production use.
For example:
- GeminiProvider
- OpenAICompatibleProvider
"""